### ISSUE TITLE
Python 3.10 incompatible

### ISSUE THREAD

**Issue by marscher** [conda-forge/pims-feedstock#16]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There is a proposed fix merged in the PIMS repo, but not yet released. We could add a patch here for Python 3.10 (its just a minor incompatibility about iterables.abc).

### Installed packages

```shell
Package  Version  Build         Channel       Size
──────────────────────────────────────────────────────
pims       0.5  pyh9f0ad1d_1  installed
```

### Environment info

```shell
conda info
```

**Comment by mrakitin** [comment]
It might have been resolved via the https://github.com/conda-forge/pims-feedstock/pull/18 version build. We use `pims` in https://github.com/conda-forge/csxtools-feedstock/pull/5, and it passes now for Python 3.10.

**Comment by marscher** [comment]
You're absolutely right! Thanks.
